# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   game_controller:
       class: Game\AppBundle\Controller\GameController
       calls:
            - [setContainer, ["@service_container"]]
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
